# # # # # # # # # # # # # # # # # # # # # # # # # #
#
# This file has to be stored in the same directory
# as the Makefile.
#
# # # # # # # # # # # # # # # # # # # # # # # # # #
#
# BITWIDTH
# Set architecture bitwidth: 32 / 64
#
# The bitwidth can either be set manually here or 
# by using the make targets 'set32' and 'set64'.
#
# # # # # # # # # # # # # # # # # # # # # # # # # #

BITWIDTH := 32

# # # # # # # # # # # # # # # # # # # # # # # # # #
#
